<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <Compile Remove="Devices\LuminousDevices\Inte\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="Devices\LuminousDevices\Inte\**" />
    <None Remove="Interfaces\**" />
    <None Remove="Devices\LuminousDevices\Inte\**" />
  </ItemGroup>

</Project>
