<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\SmartHouse.FaraoniMortani.Application\SmartHouse.FaraoniMortani.Application.csproj" />
    <ProjectReference Include="..\src\SmartHouse.FaraoniMortani.Domain\SmartHouse.FaraoniMortani.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repositories\Devices\LuminousDevice\Lamps\Json\" />
    <Folder Include="Repositories\Devices\LuminousDevice\Lamps\Csv\" />
  </ItemGroup>

</Project>
